[package]
name = "haversine-redux"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
no_std = ["libm"]

[dependencies]
libm = {version = "0.2.2", optional = true}