name: Rust

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Cargo Hack
      uses: bruxisma/setup-cargo-hack@v1.0.2
    - name: Build
      run: cargo hack build --feature-powerset --verbose --examples
    - name: Run tests
      run: cargo hack test --feature-powerset --verbose 
    - name: Build docs
      run: cargo doc --verbose
